#pragma once

#include "mainMenu.h"
#include <iomanip>
#include "raylib.h"
#include <string>
#include "intro.h"
#include "characterPick.h"
#include "questions.h"
#include "userConfirm.h"
#include "getStation.h"
#include "particlePick.h"
#include "userName.h"
#include "readyForQuiz.h"
#include "higgsFieldGame.h"
#include "pickPlanet.h"
#include "gameQuiz.h"
#include "natureScript.h"
#include "planetGame.h"
